### ISSUE TITLE
ACC计算问题

### ISSUE THREAD

**Issue by Dou-Yuxiao** [fire717/movenet.pytorch#11]
https://github.com/fire717/movenet.pytorch/blob/f248899d974ec207dff48985e4b102190b12cde8/lib/task/task_tools.py#L261
您好大佬，打扰了，首先感谢您的分享，我想问一下您在这里说的“设为-1 且后续不参与acc计算的点” 是不是后续还是在算acc时参与计算了呀，还是说您在其他哪个地方将这些为-1的点去掉了呢？因为我其实print看这些-1的点还是参与计算了呀
https://github.com/fire717/movenet.pytorch/blob/f248899d974ec207dff48985e4b102190b12cde8/lib/utils/metrics.py#L19

希望能得到您的解释谢谢！

**Comment by fire717** [comment]
这个应该是迁移的遗留问题，还是以代码为准。

我本身的项目是所有点都会有标注的，就不存在kps_mask过滤，所以没有影响。后面为了开源重新在coco上跑，忘记清理这部分了。你可以根据需要修改~

**Comment by Dou-Yuxiao** [comment]
谢谢您的回答！
