### ISSUE TITLE
Found two problems, please take a look

### ISSUE THREAD

**Issue by zwfcrazy** [fire717/movenet.pytorch#2]
您好，为了节省时间，我就用中文说了。
首先感谢您的工作，节省了我们很多时间。
我今天才发现您开源了代码，在这之前我自己也参照您的文章进行了复现，但我还没有调出一个好的效果。
今天发现您开源之后挺激动的，立马用您的代码进行了复现，并阅读了核心实现部分。但我发现了2个问题：
1. other_keypoints的标注生成有问题，这会导致生成heatmap时other_keypoints的高斯全部都挤在第17个channel上。具体由下面这行代码导致（应该是kid2而不是kid）：
https://github.com/fire717/movenet.pytorch/blob/5806c723f1a41e57f8816c286be8888bcac5099f/scripts/make_coco_data_17keypooints.py#L204
2. 在生成keypoint regression target时，您对center周围一圈都赋值了，这与您的文章里一致。但是在计算loss时，似乎还是只使用了center那一个点的值。另外，在计算loss时，您使用了网络实际输出的center和keypoint位置来计算regression loss 和offset loss，这与centernet的做法不一致，centernet使用的是ground truth的位置。请问这些都是有意而为之的吗？

**Comment by fire717** [comment]
你好，欢迎交流。
1. 大致看了下，你说的应该是对的。其实当初我实际用的不是make_coco_data_17keypooints.py，我们场景不是17点的，这个脚本是后续为了开源加的，可能与实际有点出入，稍后我仔细看看如果的确有问题那么我会更新一版。
2.
    2.1 只使用了center一个点的值：是的，本身计算loss就是只算一个点，因为你预测的时候也是只会取一个点，周围的点是没有意义的；而之所以生成的时候要在周围一圈赋值，文章也写了“每次去取回归值的时候，由于只有一个点，学习起来比较困难，因此我是给周围一圈也赋值了”，因为如果你生成一个点的值，然后通过center+reg去取的时候很容易取到这个点旁边的值而这些值是0，学习较慢，因此我赋值一圈是为了取值的时候有意义，而不是在计算loss的时候；
    2.2 这个我的确有点记不清了，如果没记错应该是考虑到预测的时候是没有gt的，也是根据网络实际输出位置来计算，因此我在训练的时候也保持一致。如果记错了，可以用gt的话，那么建议你可以尝试下跑跑看效果，也欢迎你反馈

**Comment by zwfcrazy** [comment]
@fire717 
我现在主要也是keypoint regression学习效果不够好，有时候heatmap学得不错，但是被不太好的keypoint reg结果加权以后，可能会把heatmap给带偏。我总感觉只取一个点做监督会不会信号不够？所以我现在参考的是Centernet的稠密预测方法，参考如下几行代码：
https://github.com/xingyizhou/CenterNet/blob/2b7692c377c6686fb35e473dac2de6105eed62c6/src/lib/datasets/sample/multi_pose.py#L149
因为这边用的是ground truth取值，所以可以用周围一圈来计算loss。但实际运行下来感觉也没什么提升（尴尬）。

另外我想问一下关于other_keypoints的问题，您只在heatmap部分使用了other_keypoints，而没有在reg部分使用。我目前自己的实现没有区分中心人物和非中心人物，如果画面中有2个人，我会都训练。不知道我这种训练方法是不是没有你的训练方法效率高？

**Comment by fire717** [comment]
只在heatmap部分用是因为原始movenet只负责检测图像中心人物的关键的，因此不需要reg的时候训练、预测。当然理论上来说也是可以都训练的，这样就是一个典型的bottom-up的多人同时检测了，效率上应该是一样的，只是你是要同时检测多人而已。
另外谷歌后面也开放了多人版本的movenet模型，你如果是想做多人的，可以看看结构参考下。

**Comment by zwfcrazy** [comment]
好的，多谢答复
