### ISSUE TITLE
Support for Apple Silicon / M1 

### ISSUE THREAD

**Issue by ningelsohn** [fire717/movenet.pytorch#21]
Support for GPU-accelerated training on Apple Silicon is apparently only available as of PyTorch version 1.12

I also have other problems with running it, and before I spend hours on trying to fix it for my setup, did anybody already do it?

Sorry for already filing an issue, if there was a Q/A section I would have used that before.

thanks in advance

**Comment by fire717** [comment]
In order to running on some embedded devices, this implementation only use some normal layers or ops, and not bind to any special version libs, so I think it can be easily run at higher verison of PyTorch，you can have a try.

**Comment by ningelsohn** [comment]
I got it to work now, just for reference, how long did the training take with coda enabled?

Thanks you for replying!
