### ISSUE TITLE
Question regarding the pre-trained models

### ISSUE THREAD

**Issue by gaurvigoyal** [fire717/movenet.pytorch#3]
Hey Fire,

Thanks for the repository. It looks well made and to the point. 

About the pre-trained models, are they the same ones that google has uploaded, converted into pytorch-compatible format or are they different ones? If they are different, what are they pre-trained on?

**Comment by fire717** [comment]
the pre-trained models is trained following the readme steps, so it is surely not the same as google's, cause they use more data

**Comment by gaurvigoyal** [comment]
Alright. Thanks.
