### ISSUE TITLE
关于key_points 的mirror 方法

### ISSUE THREAD

**Issue by Galaxy-Ding** [fire717/movenet.pytorch#36]
你好作者，非常感谢你的开源code。
背景：
我想修改识别的key points 的总数，因此在改动的时候，mirror 这个地方不甚了解

问题：
在修改到 data_augment 的时候，就发现，mirror 的方法 不太了解
该代码位于lib/data/data_augment.py

`
def Mirror(src, label=None):
    """
    item = {
                     "img_name":save_name,  
                     "keypoints":save_keypoints, relative position
                     "center":save_center,
                     "other_centers":other_centers,
                     "other_keypoints":other_keypoints,
                    }
    # mirror 后左右手顺序就变了！
    """
    keypoints = label['keypoints']
    center = label['center']
    other_centers = label['other_centers']
    other_keypoints = label['other_keypoints']

    img = cv2.flip(src, 1)
    if label is None:
        return img, label

    for i in range(len(keypoints)):
        if i % 3 == 0:
            keypoints[i] = 1 - keypoints[i]
    keypoints = [
        keypoints[0], keypoints[1], keypoints[2],
        keypoints[6], keypoints[7], keypoints[8],
        keypoints[3], keypoints[4], keypoints[5],
        keypoints[12], keypoints[13], keypoints[14],
        keypoints[9], keypoints[10], keypoints[11],
        keypoints[18], keypoints[19], keypoints[20],
        keypoints[15], keypoints[16], keypoints[17],
        keypoints[24], keypoints[25], keypoints[26],
        keypoints[21], keypoints[22], keypoints[23],
        keypoints[30], keypoints[31], keypoints[32],
        keypoints[27], keypoints[28], keypoints[29],
        keypoints[36], keypoints[37], keypoints[38],
        keypoints[33], keypoints[34], keypoints[35],
        keypoints[42], keypoints[43], keypoints[44],
        keypoints[39], keypoints[40], keypoints[41],
        keypoints[48], keypoints[49], keypoints[50],
        keypoints[45], keypoints[46], keypoints[47]]
`

可以看到代码中keypoints 是写死的，但是这个规律没有找到。
如果我是 4个关键点 又或者  60 个关键点，他们都是左右分布的。我想问下，这个应该怎么修改，或者 原先是为啥要这样写的？

**Comment by fire717** [comment]
一共17个关键点，每个点用 x,y,z表示 (xy为坐标，z代表是否可见)，所以一共51个元素。
然后镜像的时候只要把左手和右手对应的index交换即可，以此类推。

**Comment by Galaxy-Ding** [comment]
非常感谢您的回答，我已经弄明白了
