### ISSUE TITLE
您好，这个movenet在coco2017验证集上的map多少啊？

### ISSUE THREAD

**Issue by APeiZou** [fire717/movenet.pytorch#4]
您好，这个movenet在coco2017验证集上的map多少啊？

**Comment by fire717** [comment]
没有测过mAP，因为这个是单人检测，不是用的COCO的原始数据，需要裁剪，且参考Google过滤了大于3人的图片。

**Comment by APeiZou** [comment]
您好，最终的实现是基于heatmap的还是基于坐标直接回归的啊？



在 2021-12-20 08:51:08，"Mr.Fire" ***@***.***> 写道：

没有测过mAP，因为这个是单人检测，不是用的COCO的原始数据，需要裁剪，且参考Google过滤了大于3人的图片。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fire717** [comment]
heatmap
z这个你随便看下代码就知道了
