### ISSUE TITLE
About fine tuning

### ISSUE THREAD

**Issue by MyDuan** [fire717/movenet.pytorch#46]
Hi, I want to use your pre-trained model to fine tuning my own models by using my own dataset.
My dataset just has 9points not same as coco, is it possible to do it?

**Comment by fire717** [comment]
Yes it is possible, but origin code not support this, so you may need to do some change:
1. change data process, model structure especially head’s channels to 9 
2. load pre-trained model for those layers which not changed (shape can match)
3. train your data

**Comment by MyDuan** [comment]
Thank you, got it. 

I extract backbone parts and rewrite the header parts with my own number of points. Seems it works.
