### ISSUE TITLE
无法复现coco指标

### ISSUE THREAD

**Issue by gls0425** [fire717/movenet.pytorch#48]
这套codebase在coco17上根本无法复现acc90多的指标。可视化效果也很差。

**Comment by fire717** [comment]
你好，文章和readme均已说明，这本身就是一个轻量级小模型，直接用coco不可能达到很好的精度。谷歌官方开源的预训练模型也是加了大量额外采集的瑜伽数据才获得明显提升的。

**Comment by gls0425** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
